### ISSUE TITLE
Format for names

### ISSUE THREAD

**Issue by mrhumanzee** [jacobkap/race#2]
I'm not sure if someone else has asked this question, but is there a particular format that names have to be in for the functions _predict_gender()_ and _predict_race()_ to work? For example, does capitalization matter? Do special characters matter? Do these functions filter out name suffixes or should I remove these? Do these functions recognize hyphenated surnames? Can surnames be more than one word (i.e. double-barreled names)?

**Comment by jacobkap** [comment]
Please test all these yourselves and then if there's any issue create a new, specific issue with a reproducible example.
