### ISSUE TITLE
Race prediction not working

### ISSUE THREAD

**Issue by Charlottelqx** [jacobkap/race#3]
Hi team,

Hope this mail finds you well.

The "Predictrace" package was fantastic! I now use it for academic purposes to predict the author's gender and race. It worked on gender prediction but not race (on both GoogleColab and R studio) and kept reporting "unknown" in the race output. I hope you guys can help me check it out. :)

Best regards,
Charlotte

**Comment by jacobkap** [comment]
Hi, please provide a Minimal, Reproducible Example (MRE). https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by Charlottelqx** [comment]
Hi, I solved the issue myself. Thanks!
